# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15NrflpuqRPyjuq1pt1mCWPwxyCA8U5iO
"""

import pandas as pd

fires = pd.read_csv("data/California_Fire_Cleaned.csv", index_col = 0)

weather = pd.read_csv("data/weather_data.csv", index_col = 0)

fires.head(5)

weather.head(5)

fires.shape

weather.shape

# We need to merge on the right as some of the places weather data does not exist or could not fetched so to ensure that the model works with good data we need to
# merge right

merged = pd.merge(left=fires, right=weather, how = 'right', left_on=['FIPS', 'Latitude', 'Longitude', 'Counties','Started'], right_on=['FIPS', 'Latitude', 'Longitude', 'Counties', 'Started'])
merged.shape

drop_columns = ['Extinguished', 'Fatalities', 'CalFireIncident', 'Final', 'CountyIds', 'Injuries', 'Location', 'MajorIncident', 'PercentContained', 'Name', 'Status', 'Active Time', 'Featured', 'ArchiveYear', 'AdminUnit']

merged = merged.drop(drop_columns, axis = 1)

merged.head(5)

merged['Fire'] = True

merged.to_csv('cleaned.csv')

df = pd.DataFrame(temp, index = [0])
for i in range(0, 5):
  temp = {}
  temp['Counties'] = merged['Counties'][i]
  temp['Latitude'] = merged['Latitude'][i]
  temp['Longitude'] = merged['Longitude'][i]
  df = pd.DataFrame(temp, index = [0])
  # merged.append(df)

