# -*- coding: utf-8 -*-
"""etl_weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1imbBfUVSxx3kvYwEORyZR5_I-HfQRXmh
"""

import pandas as pd
import requests
import datetime

dataset = pd.read_csv("../data/California_Fire_Cleaned.csv")

len(dataset['Counties'])

new = dataset[['FIPS', 'Latitude', 'Longitude', 'Counties', 'Started']]

new[['Temp Day One', 'Temp Day Two', 'Temp Day Three', 'Temp Day Four', 'Temp Day Five']] = 0.0

new[['MaxTemp Day One', 'MaxTemp Day Two','MaxTemp Day Three','MaxTemp Day Four', 'MaxTemp Day Five']] = 0.0

new[['MinTemp Day One','MinTemp Day Two','MinTemp Day Three','MinTemp Day Four','MinTemp Day Five']] = 0.0

new[['Humidity Day One','Humidity Day Two','Humidity Day Three','Humidity Day Four','Humidity Day Five']] = 0.0

new.head(3)

new.dtypes

new = new.loc[new['Latitude'] != 0] # Drop latitude and longitude with 0 since california does 
new = new.loc[new['Longitude'] != 0] # not have any counties with latitude or longitude equal to 0
new = new.loc[new['Longitude'].notnull()] # remove null values
new = new.loc[new['Latitude'].notnull()]
new = new.reset_index(drop=True) # reset the index

len(new)

def storeData(a, j):
  columnName_one = ['Temp Day', 'MaxTemp Day', 'MinTemp Day', "Humidity Day"]
  columnName_two = ["One", "Two", "Three", "Four", "Five"]

  dataName = ["avgtempF", "maxtempF", "mintempF"]

  for i in range(0, 5):
    for k in range(0, 3):
      v = columnName_one[k] + " " + columnName_two[i]
      k = dataName[k]
      new[v][j] = a[i][k]
    
    avg = 0.0
    b = a[i]['hourly']
    for g in range(0, 8):
      avg += float(b[g]['humidity'])
    avg = float(avg / 8)
    v = "Humidity Day " + columnName_two[i]
    new[v][j] = avg

days = datetime.timedelta(4)
apiKEY = ""
a = {}
c = {}
for j in range(193, len(new)):
  lat = new['Latitude'][j]
  longi = new['Longitude'][j]
  startDate = new['Started'][j][0:10]
  endDate = str(pd.to_datetime(new['Started'][j]) + days)[0:10]

  requestLink = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key={key}&q={lat},{longi}&format=json&date={start}&enddate={end}".format(key = apiKEY, start = startDate, end = endDate, lat = lat, longi = longi)

  data = requests.get(requestLink)

  c = data
  try :
    a = data.json()['data']['weather']
    storeData(a, j)
  except Exception as e:
    print(e)

new = new.loc[new['Temp Day One'] != 0.0]
new = new.reset_index(drop=True) # reset the index

new.to_csv("../data/weather_data.csv")